def welcome():
    print("Hi my name is Shrut. I transferred here from Chinguacousy so this is my first year. ")
    print(" --------------------------------------")
    print("|                                      |")
    print("|                                      |")
    print("|  |||                    |||          |")
    print("|                                      |")
    print("|                                      |")
    print("|                                      |")
    print("|             ||||                     |")
    print("|                                      |")
    print("|    ||                       ||       |")
    print("|    |||||||||||||||||||||||||||       |")
    print("|                                      |")
    print("|                                      |")
    print("|                                      |")
    print(" --------------------------------------")

    print("Taking this course to learn more")

    print(" --------------------------------------")
    print("|                                      |")
    print("|                                      |")
    print("|  |||                    |||          |")
    print("|                                      |")
    print("|              ||||                    |")
    print("|                                      |")
    print("|                                      |")
    print("|    |||||||||||||||||||||||||||       |")
    print("|    ||                       ||       |")
    print("|    |||||||||||||||||||||||||||       |")
    print("|                                      |")
    print("|                                      |")
    print("|                                      |")
    print(" --------------------------------------")

    print("I have no talents")

    print(" --------------------------------------")
    print("|                                      |")
    print("|                                      |")
    print("|  |||                    |||          |")
    print("|                                      |")
    print("|                                      |")
    print("|                                      |")
    print("|             ||||                     |")
    print("|                                      |")
    print("|                                      |")
    print("|    |||||||||||||||||||||||||||       |")
    print("|    ||                       ||       |")
    print("|                                      |")
    print("|                                      |")
    print("|                                      |")
    print("|                                      |")
    print(" --------------------------------------")

welcome()