place = "China"
animal = "snake"
name = "chi wong"
noun = "bananas"
plural_noun = "marbles"
adjective = "juicy"
animal2 = "koala"
food_item = "fries"
magical_power = "invisibility"
restaurant = "taco bell"
game = "tic tac toe"
noun2 = "table"
candy = "children"
drink = "fruity splash"
superhero = "spiderman"
transportation = "helicopter"

story = f"In a land called {place}, there was a {animal} named {name}. One day, {name} decided to find {noun}. He only went with {plural_noun} to find {noun} and began the {adjective} journey. Along the way, {name} met a {animal2} who gave {name} {food_item} that has the magical power of {magical_power}. He loved the {food_item} so much he went to {restaurant} to find more and abandoned his journey to find {noun}. On the way, the animal was challenged to play {game} with his new magical power of {magical_power}. He defeated a strong {noun2} in the game of {game} and moved on with his journey. {name} found a genie who challenged him on who can eat the most {candy} and {drink} in 1 hour. {name} defeated the genie with the help of {superhero} and took {transportation} to {restaurant}. He enjoyed his {food_item} at {restaurant} and enjoyed the rest of his life."

print(story)
